import sqlite3

DB_NAME = "../tarifario.db"

conn = sqlite3.connect(DB_NAME)

conn.execute("""
CREATE TABLE IF NOT EXISTS CAT_PAISES (
    ID_PAIS INTEGER PRIMARY KEY AUTOINCREMENT,
    PAIS TEXT UNIQUE NOT NULL,
    ACTIVO INTEGER DEFAULT 1
)
""")

conn.execute("""
CREATE TABLE IF NOT EXISTS CAT_ESTADOS_NEW (
    ID_ESTADO INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PAIS INTEGER NOT NULL,
    ESTADO TEXT NOT NULL,
    ACTIVO INTEGER DEFAULT 1,
    UNIQUE (ID_PAIS, ESTADO),
    FOREIGN KEY (ID_PAIS) REFERENCES CAT_PAISES(ID_PAIS)
)
""")

conn.execute("""
CREATE TABLE IF NOT EXISTS CAT_CIUDADES (
    ID_CIUDAD INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_ESTADO INTEGER NOT NULL,
    CIUDAD TEXT NOT NULL,
    ACTIVO INTEGER DEFAULT 1,
    UNIQUE (ID_ESTADO, CIUDAD),
    FOREIGN KEY (ID_ESTADO) REFERENCES CAT_ESTADOS_NEW(ID_ESTADO)
)
""")

conn.commit()
conn.close()

print("✅ Tablas geográficas creadas correctamente.")
